### ISSUE TITLE
Column alignment is just working up to a PID length of 5

### ISSUE THREAD

**Issue by bernhardu** [berghetti/netproc#1]
Hello, I just tried netproc from the unstable debian package and on that system
there did pids exist with a length of 6 digits.
Therefore the padding is not ok anymore:
```

 netproc - 0.5.5

 Running: 19:27:35       pps tx: 10     rate tx: 6.70 Kib/s
 Processes: 18           pps rx: 9      rate rx: 76.33 Kib/s
 PID   PPS TX PPS RX    RATE TX       RATE RX       TOTAL TX      TOTAL RX   PROGRAM
 563570      7      7    3.40 Kib/s   73.01 Kib/s    279.40 Kib      5.83 Mib ...
 4621       2      2    2.36 Kib/s    2.36 Kib/s      6.85 Gib      6.86 Gib ...
 592699      1      0       539 b/s       562 b/s    549.83 Kib      8.99 Mib ...
 568004      0      0       422 b/s       422 b/s      6.51 Gib    323.76 Mib ...
 2102       0      0             0             0      3.97 Mib      3.56 Mib ...
 ...
```

E.g. `/proc/sys/kernel/pid_max` returns at this system 4194304, so it might grow up to 7 digits.
Maybe the maximum pid length could be dynamically retrieved, similar as e.g. [htop ](https://github.com/htop-dev/htop/blob/master/Process.c#L44)

**Comment by berghetti** [comment]
Hi,
thanks for reporting,
and also for the suggestion of correction.

can you test the development branch code in your box?
I made some changes for the calculation of the width of the PID column to be automatic.

`sudo apt install gcc make libncursesw5-dev`
`git clone -b dev https://github.com/berghetti/netproc.git; cd netproc; make; sudo make install`

**Comment by bernhardu** [comment]
Hello berghetti,
thanks for the fast response. I made a short test inside a VM and it looks nice now.
```
 netproc - 0.5.5

 Running: 00:07:02       pps tx: 5385   rate tx: 3.64 Mib/s
 Processes: 2            pps rx: 7992   rate rx: 1 Gib/s
     PID PPS TX PPS RX    RATE TX       RATE RX       TOTAL TX      TOTAL RX   PROGRAM
 1027188   5382   7989    3.63 Mib/s       1 Gib/s      4.32 Mib      1.18 Gib ssh ...
  766791      3      3    8.92 Kib/s    1.31 Kib/s    262.36 Kib     91.04 Kib sshd: benutzer [priv]
```

You can get to the point with 6 digits quite fast by running this `while true; do /bin/true & done`.
After some minutes it was possible to reach 7 digits too.
