### ISSUE TITLE
strange rendering probably on long process names

### ISSUE THREAD

**Issue by archenroot** [berghetti/netproc#5]
I am not sure what causes it, but time to time the rendered table disappears and its filled with this:
![image](https://user-images.githubusercontent.com/553512/129232359-c3a8d2e5-b93f-461f-baca-87dae3837c86.png)

I think its because some very long processes and I found the content by ps -ef |grep val:
`opt/slack/slack --type=utility --utility-sub-type=audio.mojom.AudioService --field-trial-handle=17156042122895987549,13589873895091716108,131072 --enable-features=WebComponentsV0Enabled --disable-features=CertVerifierService,CookiesWithoutSameSiteMustBeSecure,HardwareMediaKeyHandling,RequestInitiatorSiteLockEnfocement,SameSiteByDefaultCookies,SpareRendererForSitePerProcess,WebRtcHideLocalIpsWithMdns --lang=en-US --service-sandbox-type=none --enable-crash-reporter=81220138-9cb2-4001-8cec-5137361b41ea,no_channel --global-crash-keys=81220138-9cb2-4001-8cec-5137361b41ea,no_channel,_productName=Slack,_version=4.14.0 --standard-schemes=app,slack-webapp-dev --enable-sandbox --secure-schemes=app,slack-webapp-dev --bypasscsp-schemes=slack-webapp-dev --cors-schemes=slack-webapp-dev --fetch-schemes=slack-webapp-dev --service-worker-schemes=slack-webapp-dev --streaming-schemes --shared-files=v8_context_snapshot_data:100`

**Comment by berghetti** [comment]
Hi,
you can check if the dev branch fix the bug?
`git clone -b dev https://github.com/berghetti/netproc.git`

Thanks.

**Comment by archenroot** [comment]
Seems fixed.
