### ISSUE TITLE
Some processes are hidden

### ISSUE THREAD

**Issue by archenroot** [berghetti/netproc#7]
So I have mounted to storage via sfp+ 10gbit card to nas, I am also interested in monitoring this more infrastructure-related processes bandwidth. I can see the traffic in bmon, but net proc doesn't show anything.
![image](https://user-images.githubusercontent.com/553512/129439562-8a8a7f84-b309-4ff5-ae20-de9b98a95c97.png)

**Comment by berghetti** [comment]
Hi,
i have a possibility,

it is an **ipv6** or **ipv4 traffic mapped over ipv6 traffic**,
if it is the second case, we will see in the sniffer an ipv4 traffic although the kernel treats it as ipv6,
see **/proc/net/tcp6** to check if the connection is over ipv6,
netproc does not support ipv6 (yet).

Thanks.

**Comment by archenroot** [comment]
good catch :-)
![image](https://user-images.githubusercontent.com/553512/129456923-12d0dd4b-e7e6-4e9b-aff1-f87a962c51c3.png)

**Comment by archenroot** [comment]
I think its the second case: ipv4 traffic mapped over ipv6 traffic

**Comment by berghetti** [comment]
I noticed that you have the netproc version is 0.6.0,
after your issue #5,
released version 0.6.2

**Comment by archenroot** [comment]
Aah, I was playing with branches. Will update. I have freeze commit in
gentoo package. Thx for note
